### ISSUE TITLE
Does not compile :(

### ISSUE THREAD

**Issue by cgueret** [wwaites/py4s#1]
Here is what I get when trying to compile py4s :

cgueret@eculture2:~/software/py4s$ python setup.py build
running build
running build_py
running build_ext
cythoning _py4s.pyx to _py4s.c
## Error converting Pyrex file to C:

...
    fs_row *fs_query_fetch_header_row(fs_query *q)
    fs_row *fs_query_fetch_row(fs_query *q)

cdef extern from "frontend/import.h":
    int fs_import_stream_start(fsp_link *link, char *model_uri, char *mimetype, int has_o_index, int *count)
    int fs_import_stream_data(fsp_link *link, unsigned char *data, size_t count)
##                                                                       ^

/home/cgueret/software/py4s/_py4s.pxd:113:71: Expected ')'
## Error converting Pyrex file to C:

...
cdef class _Cursor:
    cdef py4s.fsp_link *_link
    cdef py4s.fs_query_state *_qs
    cdef py4s.fs_query *_qr
    cdef char *_query
    cdef bool _transaction
##           ^

/home/cgueret/software/py4s/_py4s.pyx:72:11: Syntax error in C variable declaration
building '_py4s' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DHAVE_LAQRS=1 -DHAVE_RASQAL_WORLD=1 -DUSE_AVAHI=1 -Isrc -I/home/cgueret/local/include/glib-2.0 -I/home/cgueret/local/lib/glib-2.0/include -I/home/cgueret/local/include -I/home/cgueret/local/include/rasqal -I/usr/include/python2.5 -c _py4s.c -o build/temp.linux-x86_64-2.5/_py4s.o -std=gnu99
gcc: _py4s.c: No such file or directory
gcc: no input files
error: command 'gcc' failed with exit status 1

**Comment by wwaites** [comment]
What version of Cython are you using? It won't build with 0.11. Need 0.12

**Comment by cgueret** [comment]
It's a 0.9.8
I'll see if I can update it

**Comment by cgueret** [comment]
Ok, it works with 0.12.1 :-)
Sorry for the false alarm

**Comment by wwaites** [comment]
Good show! Any more problems just let us know.
